### PR TITLE
update starter plan instructions - note only v0.18.1 + gifs

### PR DESCRIPTION
**Pull request by horeaporutiu**
Added relevant details which I have answered on many stack over flow posts:
1) Starter plan only works with Composer v0.18.1
2) Use UI to easily add certificates
3) it's called enrollSecret not 'admin secret'
4) incorrect steps in step 3: adding certificates to Starter plan instance (no mention of syncing certificates to channel)
5) mention that you download connection profile (this is not mentioned at all, but is a extremely important point.)
6) add gifs to show how to navigate blockchain platform (extremely useful for new users)
7) show how to check chaincode logs at the end, to ensure that your .bna is synced.
8) mention that if you have the common error (this has been asked on stack over flow several times) when you start the network, that you just wait a minute and try again. 
9) tell them congrats at the end :)

### CODE REVIEW

**Comment by horeaporutiu** [comment]
Hi @wjzhengsh I have made some changes to the starter plan instructions for deploying a business network. 

The reason I have submitted these changes is I think the instructions can be more clear. For example, there is no mention that Starter Plan only works for Composer 0.18.1, no mention that you must download connection profile from blockchain instance and then be in the same directory as the connection profile for the first step. Also, the secret is named 'enrollSecret' not 'admin secret'. Furthermore, I see there is an open PR for this, but there is no mention of synching the channels after restarting the peers. I also added gifs for easy navigation. I have answered StackoverFlow questions about these instructions, so I am hoping by adding this PR, it will be more clear for more users. Thanks for your help :), I really love this platform!

All of the changes I submitted are based on my recent blog, which I show users how to deploy a custom business network to Starter Plan: They are based on my blog here: https://hackernoon.com/deploy-a-business-network-on-free-ibm-blockchain-starter-plan-93fafb3dd997

-Horea

**Comment by wjzhengsh** [comment]
@horeaporutiu Thanks a lot for submitting this PR.  My doc team has already working on this piece of information.  Therefore, to avoid content conflict, I'll not merge your PR here directly, but combine your changes to our updates.  Let me know if you have any concerns.

**Comment by horeaporutiu** [comment]
@mataide Glad you found this PR useful. Spent a boatload of time developing these steps to be as clear as possible, and taking screenshots and making gifs so that even novice developers can stand up this starter plan :)

**Comment by wjzhengsh** [comment]
@horeaporutiu Thanks a lot for contributing to the documentation.  Your changes are merged and will show up after the next doc build (around 2 hours).

**Pull request merged**
